-- 0022_hail_menu.sql — GENERATED by scripts/generate-menu-seed.mjs. Do not edit by
-- hand; edit src/lib/cafe/hail-menu.ts and re-run the script.
--
-- The two cash registers and the HAIL menu transcribed from the owner's
-- Adobe XD design file. Prices are IQD sell prices; cost defaults to 0 (entered
-- later in «إدارة المنتجات»). Idempotent and NON-destructive: the menu is seeded
-- only when empty, so admin edits are never clobbered on re-run.

do $$
declare
  v_cat uuid;
  v_item uuid;
  v_station uuid;
begin
  -- the two registers (0021_stations.sql creates the table)
  insert into public.stations(slug, name_ar, sort) values ('pastry', 'المعجنات والمخبوزات', 1)
    on conflict (slug) do update set name_ar = excluded.name_ar, sort = excluded.sort;
  insert into public.stations(slug, name_ar, sort) values ('cafe', 'الكافيه', 2)
    on conflict (slug) do update set name_ar = excluded.name_ar, sort = excluded.sort;

  -- seed the menu only once
  if exists (select 1 from public.menu_items) then return; end if;

  -- الخبز → pastry
  select id into v_station from public.stations where slug = 'pastry';
  insert into public.categories(name_ar, sort, station_id) values ('الخبز', 1, v_station) returning id into v_cat;
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'خبز اللوز', null, 7000, '{}'::text[], 1, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'صمون الذرة', null, 2500, '{}'::text[], 2, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'صمون اسمر', null, 2000, '{}'::text[], 3, true);

  -- الكعك → pastry
  select id into v_station from public.stations where slug = 'pastry';
  insert into public.categories(name_ar, sort, station_id) values ('الكعك', 2, v_station) returning id into v_cat;
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'كوكيز قطعة شوكولاتة', null, 2000, '{}'::text[], 1, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'كوكيز مغلف', null, 1500, '{}'::text[], 2, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'كعب غزال', null, 1000, '{}'::text[], 3, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'بقصم فواكه', null, 500, '{}'::text[], 4, true);

  -- الكيك → pastry
  select id into v_station from public.stations where slug = 'pastry';
  insert into public.categories(name_ar, sort, station_id) values ('الكيك', 3, v_station) returning id into v_cat;
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'مافن شوكولاتة مغلف', null, 500, '{}'::text[], 1, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'كيك شريحة مغلف', null, 500, '{}'::text[], 2, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'دنش', null, 500, '{}'::text[], 3, true);

  -- الشوكولاتة → pastry
  select id into v_station from public.stations where slug = 'pastry';
  insert into public.categories(name_ar, sort, station_id) values ('الشوكولاتة', 4, v_station) returning id into v_cat;
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'نستلة بلجيكي ابيض', null, 1000, '{}'::text[], 1, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'نستلة بلجيكي جوزي', null, 1000, '{}'::text[], 2, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'كرات فورمسيل بستاشيو', null, 500, '{}'::text[], 3, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'كرات سلكون بستاشيو', null, 500, '{}'::text[], 4, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'كرات سلكون لوتس', null, 500, '{}'::text[], 5, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'كرات سلكون نوتيلا', null, 500, '{}'::text[], 6, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'كرات سلكون دارك', null, 500, '{}'::text[], 7, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'دريف جوزي', null, 500, '{}'::text[], 8, true);

  -- الحلقوم → pastry
  select id into v_station from public.stations where slug = 'pastry';
  insert into public.categories(name_ar, sort, station_id) values ('الحلقوم', 5, v_station) returning id into v_cat;
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'حلقوم مستكي', null, 500, '{}'::text[], 1, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'حلقوم مكسرات', null, 500, '{}'::text[], 2, true);

  -- المعجنات → pastry
  select id into v_station from public.stations where slug = 'pastry';
  insert into public.categories(name_ar, sort, station_id) values ('المعجنات', 6, v_station) returning id into v_cat;
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'دونات', null, 1500, '{}'::text[], 1, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'سينابون رول', null, 2000, '{}'::text[], 2, true);

  -- البقلاوة → pastry
  select id into v_station from public.stations where slug = 'pastry';
  insert into public.categories(name_ar, sort, station_id) values ('البقلاوة', 7, v_station) returning id into v_cat;
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'بقلاوة مشكّل', null, 0, '{}'::text[], 1, false);

  -- الموالح → pastry
  select id into v_station from public.stations where slug = 'pastry';
  insert into public.categories(name_ar, sort, station_id) values ('الموالح', 8, v_station) returning id into v_cat;
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'اصابع موالح زعتر', null, 500, '{}'::text[], 1, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'اصابع موالح حبة سودة', null, 500, '{}'::text[], 2, true);

  -- المشروبات الساخنة → cafe
  select id into v_station from public.stations where slug = 'cafe';
  insert into public.categories(name_ar, sort, station_id) values ('المشروبات الساخنة', 9, v_station) returning id into v_cat;
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'لاتيه', null, 3500, '{}'::text[], 1, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'كراميل لاتيه', null, 4000, '{}'::text[], 2, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'فانيلا لاتيه', null, 4000, '{}'::text[], 3, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'هيزلنت «بندق» لاتيه', null, 4000, '{}'::text[], 4, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'سبانش لاتيه', null, 4000, '{}'::text[], 5, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'اسبريسو سنكل', null, 2500, '{}'::text[], 6, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'اسبريسو دبل', null, 3000, '{}'::text[], 7, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'فلات وايت', null, 3500, '{}'::text[], 8, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'كورتادو', null, 3500, '{}'::text[], 9, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'كابتشينو', null, 4000, '{}'::text[], 10, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'نيسكافيه', null, 3000, '{}'::text[], 11, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'امريكانو', null, 3500, '{}'::text[], 12, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'اسبريسو مكياتو', null, 3000, '{}'::text[], 13, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'قهوه تركيه سنقل', null, 2500, '{}'::text[], 14, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'قهوه تركيه دبل', null, 4000, '{}'::text[], 15, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'هوت شوكليت', null, 3500, '{}'::text[], 16, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'دارك موكا', null, 4000, '{}'::text[], 17, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'وايت موكا', null, 4000, '{}'::text[], 18, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'شاي كرك', null, 3000, '{}'::text[], 19, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'شاي ليمون', null, 2000, '{}'::text[], 20, true);

  -- المشروبات الباردة → cafe
  select id into v_station from public.stations where slug = 'cafe';
  insert into public.categories(name_ar, sort, station_id) values ('المشروبات الباردة', 10, v_station) returning id into v_cat;
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'ايس لاتيه', null, 3500, '{}'::text[], 1, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'ايس كراميل لاتيه', null, 4000, '{}'::text[], 2, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'ايس فانيلا لاتيه', null, 4000, '{}'::text[], 3, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'ايس هيزلنت لاتيه', null, 4000, '{}'::text[], 4, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'ايس سبانش لاتيه', null, 4000, '{}'::text[], 5, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'ايس بستاشيو لاتيه', null, 4000, '{}'::text[], 6, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'ايس امريكانو', null, 4000, '{}'::text[], 7, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'ايس كراميل مكياتو', null, 4000, '{}'::text[], 8, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'ايس دارك موكا', null, 4500, '{}'::text[], 9, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'ايس وايت موكا', null, 4500, '{}'::text[], 10, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'ايس تشوكليت', null, 4000, '{}'::text[], 11, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'كراميل فرابتشينو', null, 5000, '{}'::text[], 12, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'موكاتشينو دارك', null, 5000, '{}'::text[], 13, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'موكاتشينو وايت', null, 5000, '{}'::text[], 14, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'فروزن شيك تشوكلت', null, 5500, '{}'::text[], 15, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'فروزن شيك', null, 5500, '{}'::text[], 16, true);

  -- الموهيتو → cafe
  select id into v_station from public.stations where slug = 'cafe';
  insert into public.categories(name_ar, sort, station_id) values ('الموهيتو', 11, v_station) returning id into v_cat;
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'موهيتو رمان', null, 4000, '{}'::text[], 1, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'موهيتو فراوله', null, 4000, '{}'::text[], 2, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'موهيتو جرين ويف', null, 4000, '{}'::text[], 3, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'موهيتو خوخ', null, 4000, '{}'::text[], 4, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'موهيتو توت', null, 4000, '{}'::text[], 5, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'موهيتو بلو باشن', null, 4000, '{}'::text[], 6, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'موهيتو بلو ويف', null, 4000, '{}'::text[], 7, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'ايس تي ليمون', null, 4000, '{}'::text[], 8, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'ايس تي خوخ', null, 4000, '{}'::text[], 9, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'ايس تي كيوي', null, 4000, '{}'::text[], 10, true);

  -- السموذي → cafe
  select id into v_station from public.stations where slug = 'cafe';
  insert into public.categories(name_ar, sort, station_id) values ('السموذي', 12, v_station) returning id into v_cat;
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'سموذي مانجو', null, 5000, '{}'::text[], 1, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'سموذي اناناس', null, 5000, '{}'::text[], 2, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'سموذي فراوله', null, 5000, '{}'::text[], 3, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'سموذي توت', null, 5000, '{}'::text[], 4, true);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'سموذي باشن فروت', null, 5000, '{}'::text[], 5, true);

  -- المحاصيل المتوفرة → cafe
  select id into v_station from public.stations where slug = 'cafe';
  insert into public.categories(name_ar, sort, station_id) values ('المحاصيل المتوفرة', 13, v_station) returning id into v_cat;
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'سيدامو بومبي اثيوبي', 'محمصة سويل — معالجة مجففة · توت اسود، مانجو، ياسمين', 0, '{}'::text[], 1, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'مارتن — سلفادور', 'محمصة ممتد — معالجة مجففة · شوكولاته، بندق، جوز، كراميل، فراولة', 0, '{}'::text[], 2, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'شلشلي', 'محمصة اكتوبر — معالجة مجففة · كرز، خوخ، ياسمين', 0, '{}'::text[], 3, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'موجيانا برازيلي — كودا', 'محمصة كودا — معالجة مجففة · الجوز المحمص، حلاوة قصب السكر', 0, '{}'::text[], 4, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'ريفنسيلا نافينتي — كوستريكي', 'محمصة دريب اون — معالجة مجففة · الفاكهة الحلوة، البابايا، الاناناس', 0, '{}'::text[], 5, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'موجيانا برازيلي — بريهانت', 'محمصة بريهانت — معالجة مجففة · فانيلا، كراميل، عسل، بندق', 0, '{}'::text[], 6, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'مزيج يمني واندنوسي', 'محمصة بيت التحميص · تيراميسو، شوكلاتة داكنة، كاكو', 0, '{}'::text[], 7, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'ميرندا', 'محمصة اويو فاخرة — معالجة انفيوجن · ميرندا، يوسفي، حلاوة، عطري', 0, '{}'::text[], 8, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'تروبيكال', 'محمصة اويو فاخرة — معالجة انفيوجن · اناناس، حلاوة عسلية', 0, '{}'::text[], 9, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'مزيج لوكا', 'محمصة اويو فاخرة — معالجة انفيوز · عسل، حلاوة كراميل', 0, '{}'::text[], 10, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'كولمبي — صواع', 'محمصة صواع — معالجة مغسولة · مشمش، توت اسود، زبيب احمر، كراميل', 0, '{}'::text[], 11, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'كولمبيا كوكنت — اولالا', 'محمصة اولالا — معالجة انفيوجن · كوكنت، جوز الهند', 0, '{}'::text[], 12, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'برازيل فيمتو', 'محمصة دريب اون — معالجة انفيوجن · فيمتو', 0, '{}'::text[], 13, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'كوف تروبيكال', 'محمصة كوف — معالجة انفيوز · فواكه استوائية فاخرة', 0, '{}'::text[], 14, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'مارفينا كوكنت', 'محمصة سويل مارفينا فاخرة — معالجة انفيوجن · كوكنت جوز الهند', 0, '{}'::text[], 15, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'لابراديرا', 'محمصة سويل فاخرة — تنقيع لا هوائي · عسلية، حلاوة', 0, '{}'::text[], 16, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'روفيرا', 'محمصة سويل فاخرة — تنقيع لا هوائي · توت اسود، عنب، نبيذ', 0, '{}'::text[], 17, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'ارسيلا', 'محمصة سويل فاخرة — تنقيع لا هوائي · موز، حلاوة', 0, '{}'::text[], 18, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'البيلا اثيوبيا — روستر', 'محمصة روستر — معالجة مجففة · توت ازرق، فراولة، خوخ، عطريه', 0, '{}'::text[], 19, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'دي فروتس كولمبي كولينا', 'محمصة نيردز — معالجة مجففة · فراولة، حلاوة، فواكه مجففة', 0, '{}'::text[], 20, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'قوميز — كولمبي', 'محمصة اولالا — معالجة مجففة · تفاح، فاكهية، حلاوة واضحة', 0, '{}'::text[], 21, false);
  insert into public.menu_items(category_id, name_ar, description_ar, price, flavors, sort, is_active) values (v_cat, 'مخرج 13 — كواتيمالا واثيوبي واندنوسي', 'محمصة سلالات — معالجة مجففة · كاكو فاخر، عبق الحطب، العود', 0, '{}'::text[], 22, false);

end $$;
