-- 0027_combos_seed.sql — GENERATED by scripts/generate-menu-seed.mjs.
-- حرّر HAIL_COMBOS في src/lib/cafe/hail-menu.ts ثم أعد التوليد.

do $$
declare v_combo uuid; v_item uuid;
begin
  insert into public.combos(slug, title_ar, price, sort) values ('combo-spanish-cake', 'سبانيش لاتيه ايس + كيك', 6000, 1)
    on conflict (slug) do update set title_ar = excluded.title_ar, price = excluded.price, sort = excluded.sort
    returning id into v_combo;
  delete from public.combo_items where combo_id = v_combo;
  select id into v_item from public.menu_items where name_ar = 'ايس سبانش لاتيه';
  if v_item is null then raise exception 'combo combo-spanish-cake: missing item ايس سبانش لاتيه'; end if;
  insert into public.combo_items(combo_id, item_id) values (v_combo, v_item) on conflict do nothing;
  select id into v_item from public.menu_items where name_ar = 'كيك شريحة مغلف';
  if v_item is null then raise exception 'combo combo-spanish-cake: missing item كيك شريحة مغلف'; end if;
  insert into public.combo_items(combo_id, item_id) values (v_combo, v_item) on conflict do nothing;

  insert into public.combos(slug, title_ar, price, sort) values ('combo-icechoc-donut', 'ايس تشوكليت + دونات', 7000, 2)
    on conflict (slug) do update set title_ar = excluded.title_ar, price = excluded.price, sort = excluded.sort
    returning id into v_combo;
  delete from public.combo_items where combo_id = v_combo;
  select id into v_item from public.menu_items where name_ar = 'ايس تشوكليت';
  if v_item is null then raise exception 'combo combo-icechoc-donut: missing item ايس تشوكليت'; end if;
  insert into public.combo_items(combo_id, item_id) values (v_combo, v_item) on conflict do nothing;
  select id into v_item from public.menu_items where name_ar = 'دونات';
  if v_item is null then raise exception 'combo combo-icechoc-donut: missing item دونات'; end if;
  insert into public.combo_items(combo_id, item_id) values (v_combo, v_item) on conflict do nothing;

  insert into public.combos(slug, title_ar, price, sort) values ('combo-mojito-cinnamon', 'موهيتو بلو باشن + سينابون رول', 8000, 3)
    on conflict (slug) do update set title_ar = excluded.title_ar, price = excluded.price, sort = excluded.sort
    returning id into v_combo;
  delete from public.combo_items where combo_id = v_combo;
  select id into v_item from public.menu_items where name_ar = 'موهيتو بلو باشن';
  if v_item is null then raise exception 'combo combo-mojito-cinnamon: missing item موهيتو بلو باشن'; end if;
  insert into public.combo_items(combo_id, item_id) values (v_combo, v_item) on conflict do nothing;
  select id into v_item from public.menu_items where name_ar = 'سينابون رول';
  if v_item is null then raise exception 'combo combo-mojito-cinnamon: missing item سينابون رول'; end if;
  insert into public.combo_items(combo_id, item_id) values (v_combo, v_item) on conflict do nothing;

  insert into public.combos(slug, title_ar, price, sort) values ('combo-americano-cookies', 'ايس امريكانو + كوكيز', 9000, 4)
    on conflict (slug) do update set title_ar = excluded.title_ar, price = excluded.price, sort = excluded.sort
    returning id into v_combo;
  delete from public.combo_items where combo_id = v_combo;
  select id into v_item from public.menu_items where name_ar = 'ايس امريكانو';
  if v_item is null then raise exception 'combo combo-americano-cookies: missing item ايس امريكانو'; end if;
  insert into public.combo_items(combo_id, item_id) values (v_combo, v_item) on conflict do nothing;
  select id into v_item from public.menu_items where name_ar = 'كوكيز قطعة شوكولاتة';
  if v_item is null then raise exception 'combo combo-americano-cookies: missing item كوكيز قطعة شوكولاتة'; end if;
  insert into public.combo_items(combo_id, item_id) values (v_combo, v_item) on conflict do nothing;

end $$;
